apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

nameSuffix: -example

commonLabels:
    app: phabricator-example

resources:
  - ingress.yaml

patchesStrategicMerge:
  - statefulset.yaml

configMapGenerator:
  - name: phabricator
    behavior: merge
    literals:
      - PABRICATOR_METAMTA_DEFAULT_ADDRESS=noreply@example.jp
    files:
      - PABRICATOR_CLUSTER_MAILERS_JSON=./files/mailers.json
