apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml

configMapGenerator:
  - name: neo4j-community
    literals:
      - AUTH_ENABLED=true
      - NEO4J_dbms_connector_bolt=7687
      - NEO4J_dbms_connector_bolt_listen_address=0.0.0.0:7687
      - NEO4J_dbms_connector_bolt_advertised_address=localhost:7687
      - NEO4J_dbms_connector_http=7474
      - NEO4J_dbms_connector_http_listen_address=0.0.0.0:7474
      - NEO4J_dbms_connector_http_advertised_address=localhost:7474

secretGenerator:
  - name: neo4j-community
    literals:
      - NEO4J_AUTH=neo4j/changeme
