apiVersion: v1
kind: Service
metadata:
  name: neo4j-community
  labels:
    app: neo4j-community
spec:
  selector:
    app: neo4j-community
  clusterIP: None
  ports:
    - name: browser
      protocol: TCP
      port: 7474
    - name: bolt
      protocol: TCP
      port: 7687
  type: ClusterIP
