apiVersion: v1
kind: Service
metadata:
  name: phabricator
  labels:
    app: phabricator
spec:
  selector:
    app: phabricator
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
