apiVersion: v1
kind: Service
metadata:
  name: ldap-self-service-password
  labels:
    app: ldap-self-service-password
spec:
  selector:
    app: ldap-self-service-password
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
