apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ldap-self-service-password
  labels:
    app: ldap-self-service-password
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /lssp
            backend:
              serviceName: ldap-self-service-password
              servicePort: 80
